---
- name: apache_ssl | enable ssl module
  command: a2enmod ssl creates=/etc/apache2/mods-enabled/ssl.conf
  sudo: true
  when: ansible_os_family == "Debian"
  notify:
    - restart apache2

- name: apache_ssl | add vhost for ssl version of the site
  template: src=apache_ssl_vhost.j2 dest=/etc/apache2/sites-available/{{ webserver_hostname }}_ssl.conf
  sudo: true
  when: ansible_os_family == "Debian"
  notify:
    - restart apache2

- name: apache_ssl | enable the new site
  command: a2ensite {{ webserver_hostname }}_ssl.conf creates=/etc/apache2/sites-enabled/{{ webserver_hostname }}_ssl.conf
  sudo: true
  when: ansible_os_family == "Debian"
  notify:
    - restart apache2