---
- hosts: all
  gather_facts: false

  pre_tasks:
  - name: Load Vlad settings file
    include_vars: "{{ item }}"
    with_first_found: vlad_settings_files

  tasks:
  - fail: msg="The system may not be provisioned according to the CMDB status."
    when: local_ip_address is not defined

  - name: local actions | write local hosts.ini file
    template: src=templates/host.j2 dest=../host.ini
    delegate_to: 127.0.0.1

  - name: local actions | remove reference of host from local hosts file
    lineinfile:
        dest='{{ hosts_file_location }}'
        state=absent
        regexp='.*?\s{{ webserver_hostname }} {{ webserver_hostname_alias }} adminer.{{ webserver_hostname }} xhprof.{{ webserver_hostname }} logs.{{ webserver_hostname }}'
    delegate_to: 127.0.0.1
    sudo: true

  - name: local actions | add reference of host to local hosts file
    lineinfile:
        dest='{{ hosts_file_location }}'
        state=present
        line='{{ local_ip_address }} {{ webserver_hostname }} {{ webserver_hostname_alias }} adminer.{{ webserver_hostname }} xhprof.{{ webserver_hostname }} logs.{{ webserver_hostname }}'
    delegate_to: 127.0.0.1
    sudo: true

  # ssh-add

  - name: local actions | add default identities from host to guest
    local_action: command ssh-add
    when: use_host_id is defined and use_host_id == "y"

  - name: local actions | add custom identity from host to guest
    local_action: command ssh-add {{ use_host_ssh_key }}
    when: use_host_id is defined and use_host_id != "y" and use_host_id != "n"