---
- name: install redis
  apt: pkg=redis-server state=installed
  sudo: yes

- name: set redis port
  lineinfile: dest=/etc/redis/redis.conf regexp="^port = " insertafter="^port = " line="port {{ redis_port }}"
  sudo: true